# Generated by Django 2.0.3 on 2019-06-24 19:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190605_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepageMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
