# Generated by Django 2.0.3 on 2019-06-24 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_homepagemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemessage',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
